version: '3'
services:
  java:
    image: rodybothe2/java-app-bootcamp:v1.0.0
    environment:
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      - DB_SERVER=mysql
      - DB_NAME=${DB_NAME}
    ports:
      - 8080:8080
    container_name: java
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - my_network
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PWD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PWD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - my_network
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mysql
    ports:
      - 8083:80
    container_name: phpmyadmin
    networks:
      - my_network

volumes:
  mysql:

networks:
  my_network:
